export const PANEL_TOGGLE_WATCHING = 'PANEL_TOGGLE_WATCHING';
export const PANEL_CLEAR = 'PANEL_CLEAR';

export const CONTENT_FIRE = 'CONTENT_FIRE';
export const CONTENT_CONNECT = 'CONTENT_CONNECT';
export const CONTENT_CONNECT_RECEIVE = 'CONTENT_CONNECT_RECEIVE';
