export const PANEL_TOGGLE_WATCHING = 'PANEL_TOGGLE_WATCHING';
export const PANEL_CLEAR = 'PANEL_CLEAR';
export const PANEL_TOGGLE_HIDDEN = 'PANEL_TOGGLE_HIDDEN';
export const PANEL_TOGGLE_EVENT = 'PANEL_TOGGLE_EVENT';

export const CONTENT_FIRE = 'CONTENT_FIRE';
export const CONTENT_PAGE = 'CONTENT_PAGE';
export const CONTENT_CONNECT = 'CONTENT_CONNECT';
export const CONTENT_CONNECT_RECEIVE = 'CONTENT_CONNECT_RECEIVE';
